
# Milestone 1

## Lincoln Brown

## DSC540

## Professor Williams


### Moonlight's effects on crime in Chicago

### Project Subject: 

I have always heard that crime is higher during the full moon. I want to investigate this claim against the last year's crime data for Chicago, compared to the full moon cycles and also weather patterns for the area to see if there is any validity to the claim that crime rates are higher during the full moon. 

I want to include weather to see if visibility or inclimate weather seems to have any effect on the frequency of crime. I am going to compare Full Moons, New Moons, and the phases in between. I am also going to look for things like visibility and the proximity to Earth to see if there are any patterns.


## Flat File Dataset

My first dataset is my flat file (CSV) and will also be the largest. It is the past year's crime statistics for the City of Chicago, Illinois. 
I got this from the website: https://www.chicago.gov/city/en/dataset/crime.html

This data only contains the last year to date, so my dataset reaches from September 2022 to September 2023.

Since I have the data readily available, here is a preview:

In [67]:
import pandas as pd

chicago_crime_df = pd.read_csv("./TermProject/ChicagoCrime.csv")
chicago_crime_df.head(10)

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,JF462937,11/03/2022 07:00:00 PM,031XX S ASHLAND AVE,0860,THEFT,RETAIL THEFT,SMALL RETAIL STORE,N,N,912,12.0,06,NaN,NaN,NaN,NaN,NaN
1,JF463363,11/03/2022 09:00:00 PM,025XX N ELSTON AVE,0860,THEFT,RETAIL THEFT,DEPARTMENT STORE,N,N,1432,1.0,06,NaN,NaN,NaN,NaN,NaN
2,JF461531,11/03/2022 01:00:00 PM,028XX N MERRIMAC AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,STREET,N,N,2511,30.0,14,NaN,NaN,NaN,NaN,NaN
3,JF407237,09/21/2022 02:30:00 PM,006XX N MICHIGAN AVE,0860,THEFT,RETAIL THEFT,DEPARTMENT STORE,N,N,1834,42.0,06,NaN,NaN,NaN,NaN,NaN
4,JF502909,12/08/2022 11:30:00 AM,021XX N ELSTON AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,OTHER (SPECIFY),N,N,1432,32.0,11,NaN,NaN,NaN,NaN,NaN
5,JF491558,11/18/2022 04:50:00 AM,007XX S Wells St,0810,THEFT,OVER $500,RESIDENCE - GARAGE,N,N,123,25.0,06,NaN,NaN,NaN,NaN,NaN
6,JF452314,10/28/2022 04:23:00 AM,0000X E CONGRESS PKWY,0820,THEFT,$500 AND UNDER,STREET,N,N,113,4.0,06,NaN,NaN,NaN,NaN,NaN
7,JG205676,12/31/2022 07:00:00 AM,065XX S SEELEY AVE,0890,THEFT,FROM BUILDING,SCHOOL - PUBLIC BUILDING,N,N,726,16.0,06,NaN,NaN,NaN,NaN,NaN
8,JG261559,05/06/2023 02:25:00 PM,020XX N damen ave,0890,THEFT,FROM BUILDING,SMALL RETAIL STORE,N,N,1432,32.0,06,NaN,NaN,NaN,NaN,NaN
9,JF464597,11/03/2022 08:30:00 AM,013XX E 62ND ST,0810,THEFT,OVER $500,RESIDENCE,N,N,314,20.0,06,NaN,NaN,NaN,NaN,NaN

In [68]:
# Number of rows and columns in flat file dataset
df_shape = chicago_crime_df.shape

print(f"Number of rows: {df_shape[0]}")
print(F"Number of columns {df_shape[1]}")

Number of rows: 256929
Number of columns 17


## Website Dataset

My second dataset will be Moon Phase data I am going to scrape from a table on the web page: https://moonblink.info/Eclipse/astro/table/2022 and https://moonblink.info/Eclipse/astro/table/2023

Since the crime data spans the last 12 months, I will need to scrape moon data for both 2022 and 2023. 

This dataset contains 7 columns and 51 rows per year.


## API Dataset

The final dataset is the Weather API. I looked at numerous sites for this data and found the website Visual Crossing will meet my needs:
https://www.visualcrossing.com/weather/weather-data-services#

They allow up to 1000 records per day and after some modifications, I was able to download JSON records for each month I require.

In [69]:
import json

# I will just load one month in so the dataset can be observed
json_file = "TermProject/WeatherData/09_2022.json"
with open(json_file, "r") as file:
    data = file.readlines()

json_data = ""
# Send it over to json.loads to make it easier to work with
for item in data:
    json_data = json.loads(item)

# First dataframe
json_df = pd.DataFrame(json_data)
print(f"Number of rows: {json_df.shape[0]}")
print(f"Number of columns: {json_df.shape[1]}")
print(json_df.columns)
# Well those columns don't look like the data I'm after.
# It is buried, so I need to extract the JSON I'm looking for.

# Each day's weather data resides as a series in the 'days' column
json_df['days']
sept_days = []
# Create a list so that I don't need to concatenate a bunch of df's together
for item in json_df['days']:
    sept_days.append(item)

# Using a list of dicts, I will create a dataframe for September 2022
Sept22_df = pd.DataFrame.from_dict(sept_days, orient='columns')
print(Sept22_df.head())
print(f"Number of rows: {Sept22_df.shape[0]}")
print(f"Number of columns: {Sept22_df.shape[1]}")

Number of rows: 30
Number of columns: 8
Index(['queryCost', 'latitude', 'longitude', 'resolvedAddress', 'address',
       'timezone', 'tzoffset', 'days'],
      dtype='object')
     datetime  tempmax  tempmin  feelslike  humidity  precip  precipprob  \
0  2022-09-01     31.4     20.7       26.2      57.1   0.000         0.0
1  2022-09-02     30.3     22.1       26.5      57.9   0.000         0.0
2  2022-09-03     31.3     21.8       25.3      66.1   0.000         0.0
3  2022-09-04     23.2     21.3       22.2      77.7   2.678       100.0
4  2022-09-05     22.1     20.3       21.2      76.3   0.196       100.0

   windgust  windspeed  winddir  ...  visibility  solarradiation  \
0      33.7       20.9    236.3  ...        16.0            79.0
1      40.6       23.9    195.1  ...        16.0            81.0
2      42.5       24.4    333.5  ...        16.0            64.9
3      38.9       25.6     32.1  ...        15.8            19.6
4      29.5       20.7     31.9  ...        16.0            17.6

   windspeedmax  windspeedmean   sunrise    sunset moonphase  \
0          20.9           11.6  06:16:17  19:24:00      0.19
1          23.9           14.0  06:17:18  19:22:20      0.23
2          24.4           15.5  06:18:20  19:20:39      0.25
3          25.6           19.5  06:19:22  19:18:58      0.30
4          20.7           17.5  06:20:24  19:17:16      0.33

         conditions                                        description  \
0  Partially cloudy                  Partly cloudy throughout the day.
1  Partially cloudy                  Partly cloudy throughout the day.
2  Partially cloudy                  Becoming cloudy in the afternoon.
3    Rain, Overcast  Cloudy skies throughout the day with rain in t...
4    Rain, Overcast  Cloudy skies throughout the day with early mor...

  preciptype
0        NaN
1        NaN
2        NaN
3     [rain]
4     [rain]

[5 rows x 21 columns]
Number of rows: 30
Number of columns: 21


## Relationships

The datasets are related by their location and their date. The flat file contains all of the reported incidents for Chicago. Using this information, I can aggregate the number of incidents by day and then compare the weather and the moon phase for that particular day.


## Plan of Attack

I will be pulling from all three datasets into a new dataframe. I plan on taking the number of incidents that occur and creating a count for each day. This should help me establish a baseline that I can then use to compare whether or not there is a difference in the number of crimes that occur on a full moon or not. I will also be using the weather in conjunction with the moon phase to see if that has an impact as well. 

The ethical implications of this project are that even if I do find something of statistical significance, it does not necessarily imply that a full moon causes more crime to occur. I also want to be sure that I point out that I used Chicago because the dataset was available. I am grateful that the City of Chicago makes this data publicly available for research. I may also subset the data to look at violent crime versus other types of crime because I think it would be interesting to see if there are any patterns there. 

I am curious if one year's worth of crime data will be enough to draw any significant conclusions from due to the fact that there are a limited number of full moons in a year. I would have liked to have three to five years worth of data, but I was unable to find datasets to support this. I also investigated other cities crime statistics as potential sources for more data, but I was unable to find comparable datasets. 

One area that might prove challenging is dividing the types of crime into violent and nonviolent categories. Another area that I presume will take some work is getting all of the weather data into one dataframe. While it is certainly doable, it will take some time to get it all sorted out and loaded. I also will have quite a few NaN values to deal with in my flat file and API datasets. Handling those will likely lead to dropping some columns and substituting my own values in. 

Overall, I am excited for this project and think that the datasets I have chosen will be good work with and will meet the project's milestone requirements.